<?php
/** @noinspection PhpUnused
 * @noinspection ReturnTypeCanBeDeclaredInspection
 */
namespace eftec\exampleticket\repo;

use Exception;

/**
 * Generated by PdoOne Version 2.2.2 Date generated Tue, 18 Aug 2020 11:33:02 -0400. 
 * EDIT THIS CODE.
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class TicketsRepo
 * <pre>
 * $code=$pdoOne->generateCodeClassRepo(''tickets'',''eftec\exampleticket\repo'','array('tickets'=>'TicketsRepo',)','''');
 * </pre>
 */
class TicketsRepo extends AbstractTicketsRepo
{
    const ME=__CLASS__; 
    
  
    
}