<?php
/** @noinspection PhpUnused */

namespace eftec\exampleticket\repo;

use eftec\PdoOne;
use eftec\_BasePdoOneRepo;



/**
 * Generated by PdoOne Version 1.37
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class TicketsRepo
 */
class TicketsRepo extends _BasePdoOneRepo
{
    const TABLE = 'tickets';
    const PK = 'IdTicket';
    const ME=__CLASS__;

    public static function getDef() {
        return [
            'IdTicket' => 'int not null auto_increment',
            'User' => 'varchar(50)',
            'Title' => 'varchar(50)',
            'Description' => 'varchar(200)'
        ];
    }
    public static function getDefKey() {
        return [
            'IdTicket' => 'PRIMARY KEY'
        ];
    }
    public static function getDefFK($structure=false) {
        if ($structure) {
            return [

            ];
        }
        /* key,refcol,reftable,extra */
        return [

        ];
    }
    public static function factory() {
        $recursive=static::getRecursive();
        return [
            'IdTicket'=>0,
            'User'=>'',
            'Title'=>'',
            'Description'=>''
        ];
    }
    public static function factoryNull() {
        return [
            'IdTicket'=>null,
            'User'=>null,
            'Title'=>null,
            'Description'=>null
        ];
    }

}